# when to go
on:
  push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say-Hello
        run: echo "Hello world!"
      - name: Install-packages
        run: sudo apt install fortune
      - name: get-fortune
        run: fortune
      - name: Show-files
        run: ls
      - name: get-repo-contents
        uses: actions/checkout@v3
      - name: post-checkout
        run: ls

