name: my-first-flow
on:
  push:
    branches: [main]
    workflow-dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # - docker login -u wsukduncan -pass mysupersecret
        # this would "hard code" secret values and they would be publicly viewable by looking at the workflow file (== bad)
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SILLY_SECRET }}
        run: |
          echo "$SILLY_SECRET"
